apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sntgchns
  name: barcos-agnelli-deployment
  labels:
    apply: "true"
    app: barcos-agnelli
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: barcos-agnelli
  template:
    metadata:
      labels:
        app: barcos-agnelli
    spec:
      containers:
      - name: barcos-agnelli
        image: sntgchns/barcos-agnelli:k8s
        imagePullPolicy: Never
        resources:
          requests:
            memory: 60Mi
            cpu: "20m"
          limits:
            memory: 120Mi
            cpu: "100m"
        ports:
        - containerPort: 15000
        envFrom:
        - configMapRef:
            name: sntgchns-config
        - secretRef:
            name: sntgchns-secret
        readinessProbe:
          httpGet:
            path: /
            port: 15000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 15000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
